---
name: Release

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "v*.*.*"

permissions: {}

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
      - name: Get changelog
        id: changelog
        uses: simbo/changes-since-last-release-action@45883b23a1c40599d6967b447b919a5663aaf23d # v1
      - name: Create release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            # Changelog

            ${{ steps.changelog.outputs.log }}
          draft: false
          prerelease: false
      - name: Bump tags
        uses: fischerscode/tagger@5ca3fa63ce3003fb7183cae547644b29f3b632be # v0
        with:
          prefix: v
